name: Hello world workflow
on: 
  push:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v4

      - name: List files in the repository
        run: ci/build-app.sh

      - name: Test
        run: ci/unit-test-app.sh
      
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
